export const RETRIEVE_RECOMMENDED_ARTICLES_SUCCESS = 'RETRIEVE_RECOMMENDED_ARTICLES_SUCCESS';
export const RETRIEVE_CATEGORY_ARTICLES_SUCCESS = 'RETRIEVE_CATEGORY_ARTICLES_SUCCESS';
export const RETRIEVE_SUBJECT_ARTICLES_SUCCESS = 'RETRIEVE_SUBJECT_ARTICLES_SUCCESS';
export const RETRIEVE_CATEGORY_SUBJECT_ARTICLES_SUCCESS = 'RETRIEVE_CATEGORY_SUBJECT_ARTICLES_SUCCESS';
export const RETRIEVE_SEARCH_ARTICLES_SUCCESS = 'RETRIEVE_SEARCH_ARTICLES_SUCCESS';

export const RETRIEVE_CATEGORIES_SUCCESS = 'RETRIEVE_CATEGORIES_SUCCESS';
export const RETRIEVE_SUBJECTS_SUCCESS = 'RETRIEVE_SUBJECTS_SUCCESS';
export const RETRIEVE_JOURNALISTS_SUCCESS = 'RETRIEVE_JOURNALISTS_SUCCESS';

